# Generated by Django 5.2.12 on 2026-04-12 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='avaliability_calendar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
