# Generated by Django 5.2.12 on 2026-04-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_remove_listingimage_listing_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='avaliability_calendar',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
