# Generated by Django 5.2.12 on 2026-04-20 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_review'),
        ('transactions', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='transaction',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='transactions.transaction'),
        ),
    ]
