# Generated by Django 5.2.12 on 2026-04-27 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_alter_review_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='url',
            field=models.ImageField(help_text='Изображение предмета', upload_to='items/%Y/%m/%d/'),
        ),
    ]
