# Generated by Django 5.2.12 on 2026-04-27 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_alter_itemimage_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemimage',
            old_name='url',
            new_name='image',
        ),
    ]
