# Generated by Django 5.2.12 on 2026-05-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_rename_url_itemimage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('pickup', 'pickup'), ('mail', 'mail')], default='pickup', max_length=6),
        ),
        migrations.AddField(
            model_name='item',
            name='max_active_transactions',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
