# Generated by Django 5.2.12 on 2026-05-04 11:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_item_delivery_method_item_max_active_transactions'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='viewhistory',
            options={'ordering': ['-last_viewed_at'], 'verbose_name': 'История просмотра', 'verbose_name_plural': 'Истории просмотров'},
        ),
        migrations.AddField(
            model_name='viewhistory',
            name='last_viewed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='viewhistory',
            unique_together={('user', 'item')},
        ),
    ]
