# Generated by Django 5.2.12 on 2026-05-04 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0009_item_delivery_method_item_max_active_transactions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='avaliability_calendar',
            new_name='availability_calendar',
        ),
    ]
