# Generated by Django 5.2.12 on 2026-05-04 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_notification_favoriteitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='searchhistory',
            options={'ordering': ['-last_searched_at'], 'verbose_name': 'История поиска', 'verbose_name_plural': 'Истории поиска'},
        ),
        migrations.AddField(
            model_name='searchhistory',
            name='last_searched_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='searchhistory',
            name='query_text',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
