# Generated by Django 5.2.12 on 2026-05-05 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_rename_avaliability_calendar_item_availability_calendar'),
        ('listings', '0012_alter_searchhistory_options_and_more'),
    ]

    operations = [
    ]
