# Generated by Django 5.2.12 on 2026-05-18 11:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_merge_20260505_1458'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='kind',
            field=models.CharField(choices=[('favorite_available', 'Избранный предмет освободился'), ('shared_rental_joined', 'Участник присоединился к вашей групповой аренде'), ('shared_rental_approved', 'Групповая аренда одобрена владельцем'), ('shared_rental_rejected', 'Групповая аренда отклонена владельцем'), ('shared_rental_cancelled', 'Групповая аренда отменена создателем')], max_length=32),
        ),
        migrations.CreateModel(
            name='SharedRental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_start', models.DateTimeField()),
                ('planned_end', models.DateTimeField()),
                ('slots_needed', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(2)])),
                ('status', models.CharField(choices=[('collecting', 'Сбор участников'), ('approved', 'Одобрено владельцем'), ('active', 'В использовании'), ('returning', 'В процессе возврата'), ('completed', 'Завершено'), ('cancelled', 'Отменено'), ('expired', 'Истёк срок сбора')], default='collecting', max_length=12)),
                ('confirmed_received_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_returned_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_shared_rentals', to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_rentals', to='listings.item')),
            ],
            options={
                'verbose_name': 'Групповая аренда',
                'verbose_name_plural': 'Групповые аренды',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SharedRentalSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment_index', models.PositiveIntegerField()),
                ('segment_start', models.DateTimeField()),
                ('segment_end', models.DateTimeField()),
                ('joined_at', models.DateTimeField(blank=True, null=True)),
                ('participant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shared_rental_segments', to=settings.AUTH_USER_MODEL)),
                ('shared_rental', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='listings.sharedrental')),
            ],
            options={
                'verbose_name': 'Сегмент групповой аренды',
                'verbose_name_plural': 'Сегменты групповых аренд',
                'ordering': ['shared_rental', 'segment_index'],
                'unique_together': {('shared_rental', 'participant'), ('shared_rental', 'segment_index')},
            },
        ),
    ]
