# Generated by Django 5.2.12 on 2026-05-19 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_notification_kind_sharedrental_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemtype',
            name='related_types',
            field=models.ManyToManyField(blank=True, help_text='Связанные типы — для рекомендаций сопутствующих товаров. Например, к палатке свяжите спальник, горелку, фонарь.', to='listings.itemtype'),
        ),
    ]
