# Generated by Django 5.2.12 on 2026-04-13 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
