# Generated by Django 5.2.12 on 2026-04-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='is_active',
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('active', 'active'), ('returning', 'returning'), ('completed', 'completed')], default='pending', max_length=10),
        ),
    ]
