# Generated by Django 5.2.12 on 2026-04-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_remove_transaction_is_active_transaction_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected'), ('active', 'active'), ('returning', 'returning'), ('completed', 'completed')], default='pending', max_length=10),
        ),
    ]
