# Generated by Django 5.2.12 on 2026-05-04 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='planned_end',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 11, 31, 36, 663602, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='planned_start',
            field=models.DateTimeField(default=datetime.datetime(2026, 5, 4, 11, 32, 1, 183590, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
